spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #不用写协议
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/api/business/**
        - id: msg-service
          uri: lb://msg-service
          predicates:
            - Path=/api/msg/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: test
          uri: https://example.org
          predicates:
            - Path=/test/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8847