server:
  port: 8082
  servlet:
    context-path: /api/business/
spring:
  application:
    name: business-service
  datasource:
    url: jdbc:mysql://localhost:3306/miyabi_megumi?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    open-in-view: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  mail:
    host: smtp.qq.com
    username: 1084783417@qq.com
    password: hmtzeiradhbmjbjd
    port: 25
    default-encoding: UTF-8
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
    ssl: false
    timeout: 5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    generator:
      write_numbers_as_strings: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


